### ISSUE TITLE
When executing a task from MatlabConnector in fork mode, the task fails

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/connector-matlab-scilab#271]
```
[3t0@MORTADELLA;14:32:46] Failed to execute task: 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:202) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:141) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:88) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:78) 
[3t0@MORTADELLA;14:32:46] Caused by: org.ow2.proactive.scripting.ScriptException: 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.java.JavaClassScriptEngine.eval(JavaClassScriptEngine.java:126) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.java.JavaClassScriptEngine.eval(JavaClassScriptEngine.java:155) 
[3t0@MORTADELLA;14:32:46] at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scripting.Script.execute(Script.java:319) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:198) 
[3t0@MORTADELLA;14:32:46] ... 3 more 
[3t0@MORTADELLA;14:32:46] java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.rmi.server") 
[3t0@MORTADELLA;14:32:46] at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) 
[3t0@MORTADELLA;14:32:46] at java.security.AccessController.checkPermission(AccessController.java:884) 
[3t0@MORTADELLA;14:32:46] at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) 
[3t0@MORTADELLA;14:32:46] at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader$1.run(ClassLoader.java:502) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader$1.run(ClassLoader.java:500) 
[3t0@MORTADELLA;14:32:46] at java.security.AccessController.doPrivileged(Native Method) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader.defineClass1(Native Method) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader.defineClass(ClassLoader.java:760) 
[3t0@MORTADELLA;14:32:46] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) 
[3t0@MORTADELLA;14:32:46] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) 
[3t0@MORTADELLA;14:32:46] at java.net.URLClassLoader.access$100(URLClassLoader.java:73) 
[3t0@MORTADELLA;14:32:46] at java.net.URLClassLoader$1.run(URLClassLoader.java:368) 
[3t0@MORTADELLA;14:32:46] at java.net.URLClassLoader$1.run(URLClassLoader.java:362) 
[3t0@MORTADELLA;14:32:46] at java.security.AccessController.doPrivileged(Native Method) 
[3t0@MORTADELLA;14:32:46] at java.net.URLClassLoader.findClass(URLClassLoader.java:361) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
[3t0@MORTADELLA;14:32:46] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
[3t0@MORTADELLA;14:32:46] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter$ObjectStream.convert(ObjectToByteConverter.java:83) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.TaskResultImpl.computeSerializedException(TaskResultImpl.java:179) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.TaskResultImpl.<init>(TaskResultImpl.java:172) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:151) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:88) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:78) 
[3t0@MORTADELLA;14:32:46] java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.rmi.server") 
[3t0@MORTADELLA;14:32:46] at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) 
[3t0@MORTADELLA;14:32:46] at java.security.AccessController.checkPermission(AccessController.java:884) 
[3t0@MORTADELLA;14:32:46] at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) 
[3t0@MORTADELLA;14:32:46] at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader$1.run(ClassLoader.java:502) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader$1.run(ClassLoader.java:500) 
[3t0@MORTADELLA;14:32:46] at java.security.AccessController.doPrivileged(Native Method) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader.defineClass1(Native Method) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader.defineClass(ClassLoader.java:760) 
[3t0@MORTADELLA;14:32:46] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) 
[3t0@MORTADELLA;14:32:46] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) 
[3t0@MORTADELLA;14:32:46] at java.net.URLClassLoader.access$100(URLClassLoader.java:73) 
[3t0@MORTADELLA;14:32:46] at java.net.URLClassLoader$1.run(URLClassLoader.java:368) 
[3t0@MORTADELLA;14:32:46] at java.net.URLClassLoader$1.run(URLClassLoader.java:362) 
[3t0@MORTADELLA;14:32:46] at java.security.AccessController.doPrivileged(Native Method) 
[3t0@MORTADELLA;14:32:46] at java.net.URLClassLoader.findClass(URLClassLoader.java:361) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
[3t0@MORTADELLA;14:32:46] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 
[3t0@MORTADELLA;14:32:46] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
[3t0@MORTADELLA;14:32:46] at org.objectweb.proactive.core.util.converter.ObjectToByteConverter$ObjectStream.convert(ObjectToByteConverter.java:83) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.TaskResultImpl.computeSerializedException(TaskResultImpl.java:179) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.TaskResultImpl.<init>(TaskResultImpl.java:172) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.TaskResultImpl.<init>(TaskResultImpl.java:120) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:161) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:88) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:78) 
[3t0@MORTADELLA;14:32:46] Could not serialize exception as task result: 
[3t0@MORTADELLA;14:32:46] java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Users\fviale\AppData\Local\Temp\PA_JVM1763751816\local-LocalNodes_0\3\-345050725\0006224742942767879639.tmp" "write") 
[3t0@MORTADELLA;14:32:46] at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) 
[3t0@MORTADELLA;14:32:46] at java.security.AccessController.checkPermission(AccessController.java:884) 
[3t0@MORTADELLA;14:32:46] at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) 
[3t0@MORTADELLA;14:32:46] at java.lang.SecurityManager.checkWrite(SecurityManager.java:979) 
[3t0@MORTADELLA;14:32:46] at java.io.FileOutputStream.<init>(FileOutputStream.java:200) 
[3t0@MORTADELLA;14:32:46] at java.io.FileOutputStream.<init>(FileOutputStream.java:162) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.serializeTaskResult(ExecuteForkedTaskInsideNewJvm.java:64) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.fromForkedJVM(ExecuteForkedTaskInsideNewJvm.java:94) 
[3t0@MORTADELLA;14:32:46] at org.ow2.proactive.scheduler.task.executors.forked.env.ExecuteForkedTaskInsideNewJvm.main(ExecuteForkedTaskInsideNewJvm.java:78) 



```

**Comment by fviale** [comment]
In non-forked mode, the following error appears instead:
```
[53t0@192.168.56.1;14:53:42] Failed to execute task: Illegal character in opaque part at index 2: C:\tmp\ProActiveWorkflowsScheduling-windows-x64-7.5.1\bin\. 
[53t0@192.168.56.1;14:53:42] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:202) 
[53t0@192.168.56.1;14:53:42] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:141) 
[53t0@192.168.56.1;14:53:42] at org.ow2.proactive.scheduler.task.TaskLauncher.doTask(TaskLauncher.java:174) 
[53t0@192.168.56.1;14:53:42] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
[53t0@192.168.56.1;14:53:42] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
[53t0@192.168.56.1;14:53:42] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
[53t0@192.168.56.1;14:53:42] at java.lang.reflect.Method.invoke(Method.java:497) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.Service.fifoServing(Service.java:146) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:337) 
[53t0@192.168.56.1;14:53:42] at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175) 
[53t0@192.168.56.1;14:53:42] at java.lang.Thread.run(Thread.java:745) 
[53t0@192.168.56.1;14:53:42] Caused by: org.ow2.proactive.scripting.ScriptException: Illegal character in opaque part at index 2: C:\tmp\ProActiveWorkflowsScheduling-windows-x64-7.5.1\bin\. 
[53t0@192.168.56.1;14:53:42] at org.ow2.proactive.scheduler.task.java.JavaClassScriptEngine.eval(JavaClassScriptEngine.java:126) 
[53t0@192.168.56.1;14:53:42] at org.ow2.proactive.scheduler.task.java.JavaClassScriptEngine.eval(JavaClassScriptEngine.java:155) 
[53t0@192.168.56.1;14:53:42] at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249) 
[53t0@192.168.56.1;14:53:42] at org.ow2.proactive.scripting.Script.execute(Script.java:319) 
[53t0@192.168.56.1;14:53:42] at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76) 
[53t0@192.168.56.1;14:53:42] at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:198) 
[53t0@192.168.56.1;14:53:42] ... 18 more 
```
