### ISSUE TITLE
Illegal character exception when referring to the scheduler path under windows

### ISSUE THREAD

**Issue by mbenguig** [ow2-proactive/connector-matlab-scilab#278]
To reproduce it. With Matlab2016 and Windows
>PAsolve(@factorial,1)

Failed to execute task: Illegal character in opaque part at index 2: C:\workspace\scheduling\. javax.script.SimpleScriptContext@25d5110c
    at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:202)
    at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:141)
    at org.ow2.proactive.scheduler.task.TaskLauncher.doTask(TaskLauncher.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:353)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:214)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:160)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:552)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:485)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:426)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:206)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:181)
    at org.objectweb.proactive.Service.fifoServing(Service.java:146)
    at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:337)
    at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:175)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.ow2.proactive.scripting.ScriptException: Illegal character in opaque part at index 2: C:\workspace\scheduling\. TUTU org.ow2.proactive.scheduler.ext.matlab.worker.MatlabExecutable javax.script.SimpleScriptContext@25d5110c
    at org.ow2.proactive.scheduler.task.java.JavaClassScriptEngine.eval(JavaClassScriptEngine.java:126)
    at org.ow2.proactive.scheduler.task.java.JavaClassScriptEngine.eval(JavaClassScriptEngine.java:155)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
    at org.ow2.proactive.scripting.Script.execute(Script.java:319)
    at org.ow2.proactive.scripting.ScriptHandler.handle(ScriptHandler.java:76)
    at org.ow2.proactive.scheduler.task.executors.InProcessTaskExecutor.execute(InProcessTaskExecutor.java:198)
    ... 18 more

**Comment by mbenguig** [comment]
After a first fix (not committed) that replaces backslashs with forwardslashs, we get the same problem detailed in ow2-proactive/scheduling: getXSpace() methods are not available from a JavaExecutable #2502. Need to fix #2502 before considering this issue.
